"""alinhamento_supabase

Revision ID: 207dfdf6b074
Revises: 
Create Date: 2026-08-19 07:12:33.459045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207dfdf6b074'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agendamento_id'), 'agendamento', ['id'], unique=False)
    op.alter_column('categoria', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.alter_column('empresa', 'estado',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.drop_constraint(op.f('empresa_email_key'), 'empresa', type_='unique')
    op.create_index(op.f('ix_empresa_email'), 'empresa', ['email'], unique=True)
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.alter_column('servico', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('servico', 'descricao',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_servico_id'), 'servico', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_servico_id'), table_name='servico')
    op.alter_column('servico', 'descricao',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('servico', 'nome',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_email'), table_name='empresa')
    op.create_unique_constraint(op.f('empresa_email_key'), 'empresa', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('empresa', 'estado',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.alter_column('categoria', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_agendamento_id'), table_name='agendamento')
    # ### end Alembic commands ###
